version: '3.1'

services:
  personal_blog_pg:
    image: postgres:16
    container_name: personal_blog_pg
    restart: always
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432